"""change pk

Revision ID: 030cca9e6ca9
Revises: 85dc197c4704
Create Date: 2025-09-17 23:39:46.746044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '030cca9e6ca9'
down_revision: Union[str, Sequence[str], None] = '85dc197c4704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
