"""add models 2

Revision ID: a03acef2d7d2
Revises: 6c5f568e919c
Create Date: 2025-09-17 23:53:32.228956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a03acef2d7d2'
down_revision: Union[str, Sequence[str], None] = '6c5f568e919c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teammate', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'teammate', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teammate', type_='foreignkey')
    op.drop_column('teammate', 'team_id')
    # ### end Alembic commands ###
