"""init

Revision ID: 85dc197c4704
Revises: 
Create Date: 2025-09-17 23:39:13.205988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '85dc197c4704'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='用户状态 0: PENDING 1: ACTIVE 2: INACTIVE'),
    sa.Column('role', sa.String(length=20), nullable=True, comment='用户角色 user: USER admin: ADMIN guest: GUEST'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
