"""add models 3

Revision ID: f98e23fee769
Revises: a03acef2d7d2
Create Date: 2025-09-18 00:02:59.939285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f98e23fee769'
down_revision: Union[str, Sequence[str], None] = 'a03acef2d7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_teammate_user_id_team_id', 'teammate', ['user_id', 'team_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_teammate_user_id_team_id', table_name='teammate')
    # ### end Alembic commands ###
